#!/usr/bin/env bash
#This script will display information about subdomains.

print_message () {
	dig "$2"."$1" | grep -A1 "ANSWER SECTION" | tail -n +2 | awk 'match($1, /^[^.]*/) {print "The subdomain " substr($1, 1, RLENGTH) " is a " $4 " record and points to " $5}'
}

if [ $# -eq 2 ]
then
	print_message "$1" "$2"
else
	declare -a subs=("www" "lb-01" "web-01" "web-02")
	for sub in "${subs[@]}"; do
		print_message "$1" "$sub"
	done
fi
