#!/usr/bin/env bash
#install nginx
#sudo usermod -aG sudo $(whoami)

sudo apt -y update
sudo apt -y install nginx

rm /var/www/html/*
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
