#!/usr/bin/env bash
#install nginx and set a random redirection 
sudo usermod -aG sudo $(whoami)

apt -y update
apt -y install nginx

rm /var/www/html/*
echo "Holberton School" >> /var/www/html/index.html
service nginx restart

redirect_line="server {
	location /redirect_me{
		rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 redirect;
	}
"
sed -i "s/^server\s{/$redirect_line/" /etc/nginx/sites-available/default
