#!/usr/bin/env bash
#install nginx and set a random redirection 
sudo usermod -aG sudo $(whoami)

apt -y update
apt -y install nginx

rm /var/www/html/*
echo "Holberton School" >> /var/www/html/index.html

redirectline="server {\n\tlocation \/redirect_me{\n\t\trewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 redirect;\n\t}"
sed -i "s/^server\s{/$redirectline/1" /etc/nginx/sites-available/default
service nginx restart
