#!/usr/bin/env bash
# This script Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid

getoutterm() {
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit
}

getoutquit() {
    sudo rm /var/run/holbertonscript.pid
    exit
}

trap getoutterm SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap getoutquit SIGQUIT

while $1; do
    echo "To infinity and beyond"
    sleep 2
done
