#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

#for i in $(seq 0 1 9); #This does not work because shellcheck says I'm not using the variable i
for ((i=0;i<10;i+=1));
do echo 'Holberton School';
done
