#!/usr/bin/env bash
# FIZZBUZZ

for ((i=1;i<=100;i++))
do
    if ((i%3 == 0 && i%5 == 0)); then
        echo "FIZZBUZZ"
    elif ((i%3 == 0)); then
        echo "FIZZ"
    elif ((i%5 == 0)); then
        echo "BUZZ"
    else
        echo "$i"
    fi
done
