#!/usr/bin/env bash
# This scripts displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

l=$(ls)
for i in $l; do
echo "$i" | cut -d '-' -f 2
done
